### ISSUE TITLE
Determine availability

### ISSUE THREAD

**Issue by jboxman** [chingu-voyage3/bears-11#3]
What days and times is everyone available?

**Comment by mojicaj** [comment]
Sun - Thurs: 8:30am - 11am
Fri - Sat: all day depending on errands/family activities

**Comment by eolculnamo2** [comment]
Mornings 9am-1:30pm/ 12:30am-2:30am Mon-Fri.Most weekends. This weekend I have drill and the following I’m set to work Saturday.

**Comment by eolculnamo2** [comment]
My times are in the central time zone

**Comment by Renestl** [comment]
Mon-Tues, Thurs-Fri: 6-8pm CST. 
Sat: depend on obligations
Sun: Usually after 4-5pm
My daytime hours vary.

**Comment by jboxman** [comment]
Awesome, thanks all! I'll create a wiki page with this information. It may help to have this centralized somewhere.

**Comment by jboxman** [comment]
I'm going to close this for now. I recorded the information in the _Wiki_.
