### ISSUE TITLE
Define initial data model

### ISSUE THREAD

**Issue by jboxman** [chingu-voyage3/bears-11#33]
Based on the user stories so far, we have enough information to sketch out what our data model looks like.

**Comment by mojicaj** [comment]
let me know if I missed anything

Project {
  title: String,
  description: String,
  level: Number,
  type: String,
  link: String, // link to github, non-profit
}

// extended feature
User {
  username: String,
  githubId: String,
  projects: Array   // completed projects
}

**Comment by jboxman** [comment]
Cool. This is a good start. I wonder if we ought to specify an Enum for level and type in the model itself? What were our types and levels?

**Comment by mojicaj** [comment]
we didn't really discuss this in detail but we were thinking
type: clone, non-profit, Github issue - anymore?
we spoke about using the FCC/Chingu tiers for level

**Comment by jboxman** [comment]
Here's a proposed gist of what this might look like.

https://gist.github.com/jboxman/984e646f14401f09c0737939813eeffe

Let's see if this supports embeds. (No, it doesn't.)

**Comment by jboxman** [comment]
What does everyone think?
