### ISSUE TITLE
Create user stories

### ISSUE THREAD

**Issue by jboxman** [chingu-voyage3/bears-11#4]
If we're okay with the scope in #2 then next up we can devise user stories.

**Comment by jboxman** [comment]
We have 2 personas that I can think of:

* administrator (creates/manages project ideas)
* user (retrieves project idea)

What do you think?

**Comment by jboxman** [comment]
admin stories
--------------

As an admin,
I want to be able to login,
so I can access the admin interface

As an admin,
I want to be able to create a project idea,
so I can populate the database with ideas for users

As an admin,
I want to be able to edit a project idea,
so I can make changes to an idea.

As an admin,
I want to be able to delete a project idea,
so I can remove erroneously created ideas and otherwise prune the project choices

As an admin,
I want to see a list of existing project ideas,
so I know what ideas already exist in the database

As an admin,
I want to be able to filter the list of existing projects,
so I can narrow down the list of ideas to find ideas matching a particular keyword or tag or difficulty level

As an admin,
I want to be able to assign a tier to an idea,
so users know the level of effort required for implementation of an idea

**Comment by mojicaj** [comment]
@jboxman  I agree with your personas and admin stories, can't think of anything to add to those at the moment.

user story: I can select a project level

user story: I can select a type of project(clone, non-profit, Github issue)

user story: I will receive a random project idea with a description based on my criteria

user story: I can submit a project idea/request

user story: I can view a list of project ideas to select my own

**Comment by jboxman** [comment]
I've transferred these into individual issues.
