### ISSUE TITLE
Propose tech stack

### ISSUE THREAD

**Issue by jboxman** [chingu-voyage3/bears-11#6]
So, what's a tech stack to use? I think the current proposed stack is:

* React (front-end)
* Redux (front-end)
* MongoDB (Mongoose via package) (backend)
* NodeJS (backend)
* Express (backend)
* Passport (backend, module for OAuth authentication)

And to this, I'd add:

* Semantic UI React (mostly ready made UI components)
* react-redux-form (because complex forms are a challenge)

**Comment by Renestl** [comment]
Jest/Enzyme for testing since they already play well with React?

**Comment by jboxman** [comment]
Yeah, I think that makes sense. It's what everyone does today. And snapshot testing for redux.
